global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "w_ttsr"
    scrape_interval: 5s
    static_configs:
      - targets: ["app:8080"]
    metrics_path: '/metrics'
    relabel_configs: 